# Generated by Django 5.0.6 on 2024-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
