# Generated by Django 5.0.6 on 2024-06-18 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0002_system_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
